//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Facebook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://graph.facebook.com/me?fields=id&amp;{0}.
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dummy-callback-url/.
        /// </summary>
        internal static string DummyCallbackUrl {
            get {
                return ResourceManager.GetString("DummyCallbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://graph.facebook.com/oauth/access_token.
        /// </summary>
        internal static string FacebookAccessTokenUrl {
            get {
                return ResourceManager.GetString("FacebookAccessTokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Login.
        /// </summary>
        internal static string FacebookAuthenticationFormName {
            get {
                return ResourceManager.GetString("FacebookAuthenticationFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.blahblah.com/facebookcallback.aspx.
        /// </summary>
        internal static string FacebookCallbackUrl {
            get {
                return ResourceManager.GetString("FacebookCallbackUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/dialog/oauth?client_id={0}&amp;redirect_uri=https://www.facebook.com/connect/login_success.html&amp;display=popup&amp;response_type=token&amp;state={1}&amp;scope=publish_stream,offline_access.
        /// </summary>
        internal static string FacebookLoginUrl {
            get {
                return ResourceManager.GetString("FacebookLoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/logout.php?api_key={0}&amp;auth_token={1}&amp;v=1.0&amp;confirm=1.
        /// </summary>
        internal static string FacebookLogoutUrl {
            get {
                return ResourceManager.GetString("FacebookLogoutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.facebook.com/1.0/.
        /// </summary>
        internal static string FacebookNamespace {
            get {
                return ResourceManager.GetString("FacebookNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/connect/prompt_permissions.php?api_key={0}&amp;fbconnect=true&amp;v=1.0&amp;display=popup&amp;extern=1&amp;next=https://www.facebook.com/connect/login_success.html?xxRESULTTOKENxx&amp;ext_perm=.
        /// </summary>
        internal static string FacebookRequestExtendedPermissionUrl {
            get {
                return ResourceManager.GetString("FacebookRequestExtendedPermissionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://static.ak.facebook.com/pics/s_default.jpg.
        /// </summary>
        internal static string MissingPictureUrl {
            get {
                return ResourceManager.GetString("MissingPictureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.facebook.com/multi_friend_selector.php.
        /// </summary>
        internal static string SendRequestUrl {
            get {
                return ResourceManager.GetString("SendRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://graph.facebook.com/me/feed?{0}.
        /// </summary>
        internal static string Stream {
            get {
                return ResourceManager.GetString("Stream", resourceCulture);
            }
        }
    }
}
