//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBMCE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBMCE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Center Status Application.
        /// </summary>
        internal static string Twitter_Client {
            get {
                return ResourceManager.GetString("Twitter_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.jussipalo.com/fbmce.
        /// </summary>
        internal static string Twitter_ClientUrl {
            get {
                return ResourceManager.GetString("Twitter_ClientUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to axnj44mbHVIhTy0YOHreQ.
        /// </summary>
        internal static string Twitter_ConsumerKey {
            get {
                return ResourceManager.GetString("Twitter_ConsumerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xOaXnumZx1HhRE5BulJuH7LaLt0l6bgrymrerJ2k.
        /// </summary>
        internal static string Twitter_ConsumerSecret {
            get {
                return ResourceManager.GetString("Twitter_ConsumerSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/home_timeline.json.
        /// </summary>
        internal static string Twitter_FriendStatusUrl {
            get {
                return ResourceManager.GetString("Twitter_FriendStatusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/statuses/update.json.
        /// </summary>
        internal static string Twitter_StatusUrl {
            get {
                return ResourceManager.GetString("Twitter_StatusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitter.com/1.1/account/verify_credentials.json.
        /// </summary>
        internal static string Twitter_VerifyCredentialsUrl {
            get {
                return ResourceManager.GetString("Twitter_VerifyCredentialsUrl", resourceCulture);
            }
        }
    }
}
